import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Configuration will be loaded from the config file generated by the tool
// We use a fallback to empty object to prevent direct crashes if not yet initialized
let firebaseConfig = {};
try {
  // @ts-ignore
  import config from '../firebase-applet-config.json';
  firebaseConfig = config;
} catch (e) {
  console.warn("Firebase config not found. Running in offline mode.");
}

const app = initializeApp(firebaseConfig as any);
export const auth = getAuth(app);
export const db = getFirestore(app);

// Helper for Firebase connection test as per guidelines
export async function checkFirebase() {
  try {
    const { doc, getDocFromServer } = await import('firebase/firestore');
    await getDocFromServer(doc(db, 'test', 'connection'));
  } catch (error) {
    console.error("Firebase Connection Error:", error);
  }
}
